language: python
cache: pip
python:
- '3.6'
- '3.7'
- '3.8'
sudo: false
env:
  - POSTGRES_PASSWORD=
services:
  - postgresql
install:
- pip3 install . psycopg2-binary
jobs:
  fast_finish: true
script:
- python tests/runtests.py
