language: python
cache: pip
python:
- '3.5'
- '3.6'
- '3.7'
- '3.8'
sudo: false
env:
  - POSTGRES_PASSWORD=
services:
  - postgresql
install:
- pip install . psycopg2-binary
matrix:
  fast_finish: true
before_script:
  - psql -c 'create database postgres;' -U postgres
script:
- python tests/runtests.py
