language: python
cache: pip
python:
- '3.6'
- '3.7'
- '3.8'
sudo: false
env:
  - POSTGRES_PASSWORD=
services:
  - postgresql
install:
- pip3 install . psycopg2-binary selenium
jobs:
  fast_finish: true
before_script:
   - psql -c 'create database test_postgres_1;' -U postgres
script:
- python tests/runtests.py
